/// @file
/// @brief Virtual Machine C++ headers

#ifndef _H_BCX
#define _H_BCX

#include <iostream>
using namespace std;

/// @defgroup parser Syntax parser interface
/// @{

/// @name lexer interface [lex/flex]
/// @{

/// get next token from source code stream
extern int yylex();
/// current line number @see lexer option
extern int yylineno;
/// current lexeme matched
extern char* yytext;

/// @}

/// @name token macro
/// @{

/// `CMD0` zero parameters command
#define C0(X) { yylval.cmd0 = X; return CMD0; }

/// @}

/// @name parser interface [yacc/bison]
/// @{

extern int yyparse();

/// syntax error callback
extern void yyerror(const char*);

/// tokens definitions generated by yacc
#include "ypp.tab.hpp"

/// @}

/// @}

#endif // _H_BCX

